// Generated by https://quicktype.io

export interface IPokeList {
  count:    number;
  next:     string;
  previous: null;
  results:  PokeResults[];
}

export interface PokeResults {
  name: string;
  url:  string;
}
